src/Gala/CoreBundle/Entity/Photos.php
<?php

namespace Gala\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Photos
 *
 * @ORM\Table(name="photos")
 * @ORM\Entity(repositoryClass="Gala\CoreBundle\Repository\PhotosRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Photos
{
    /**
     * @Assert\Image(
     *  maxSize = "5M",
     * )
     */
    protected $file;
    
    private $tempFileName;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="extension", type="string", length=4)
     */
    private $extension;


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Set extension
     *
     * @param string $extension
     *
     * @return string
     */
    public function setExtension($extension)
    {
        $this->extension = $extension;

        return $this;
    }

    /**
     * Get extension
     *
     * @return string
     */
    public function getExtension()
    {
        return $this->extension;
    }

    public function getFileNameExt()
    {
        return $this->getId().'.'.$this->getExtension();
    }

    public function setFile(UploadedFile $file)
	{
		$this->file = $file;
		if (null !== $this->getId()) {
			$this->tempFileName = $this->getId();
			$this->extension = null;
		}
    }
    
	public function getFile()
	{
		return $this->file;
	}
    
    /**
	* @ORM\PrePersist()
	* @ORM\PreUpdate()
	*/
	public function preUpload()
	{
		if (null === $this->file) {
			return;
		}
        $this->setExtension($this->file->guessExtension());
        $this->preUpdateFile();
	}

    protected function preUpdateFile(){} // To define if specific
	
	/**
	 * @ORM\PrePersist()
	 */
	public function prePersistDate()
	{
		$this->date = new \DateTime();
		return $this;
	}
    
	/**
	* @ORM\PostPersist()
	* @ORM\PostUpdate()
	*/
	public function upload()
	{
		if (null === $this->file) {
			return;
		}

		// Si on avait un ancien fichier, on le supprime
		if (null !== $this->tempFileName) {
			$oldFile = $this->getUploadRootDir().$this->tempFileName;
			if (file_exists($oldFile)) {
				unlink($oldFile);
			}
		}

		// On déplace le fichier envoyé dans le répertoire de notre choix
		$this->file = $this->file->move(
			$this->getUploadRootDir(), // Le répertoire de destination
			$this->getFileNameExt()   // Le nom du fichier à créer
        );
		
		$this->postUpdateFile();
    }

    protected function postUpdateFile(){} // To define if specific treatment

    /**
    * @ORM\PreRemove()
    */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier
        $this->tempFileName = $this->getFileNameExt();
        $this->preRemoveFile();
    }
    
    protected function preRemoveFile(){} // To define if specific treatment

	/**
	* @ORM\PostRemove()
	*/
	public function removeUpload()
	{
        $oldFile = $this->getUploadRootDir().$this->tempFileName;
        if (file_exists($oldFile)) {
            unlink($oldFile);
        }
        $this->postRemoveFile();
    }
    
    protected function postRemoveFile(){} // To define if specific treatment

    public function getFileUri()
    {
        return $this->getUploadDir().$this->getFileNameExt();
    }

	public function getUploadDir()
	{
		// On retourne le chemin relatif vers l'image pour un navigateur
		return 'uploads/';
	}

	protected function getUploadRootDir()
	{
		// On retourne le chemin relatif vers l'image pour notre code PHP
		return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }
    
    public function __toString() {
        return $this->getFileNameExt();
    }
}

src/Gala/CoreBundle/Form/PhotosType.php
<?php
namespace Gala\CoreBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Validator\Constraints\All;

use Symfony\Component\OptionsResolver\OptionsResolver;

class PhotosType extends AbstractType
{

	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
				->add('files', FileType::class, array(
					'multiple' => true,
					'constraints' => array(
						new All(array(
							'constraints' => new Image(),
						))
					),
				))
				->add('send', SubmitType::class);
	}

    public function getName()
    {
        return 'Photos';
    }
}

src/Gala/CoreBundle/Controller/PhotosController.php
<?php

namespace Gala\CoreBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use Gala\CoreBundle\Form\DeleteType;
use Gala\CoreBundle\Form\PhotosType;
use Gala\CoreBundle\Entity\Photos;
use Gala\CoreBundle\Entity\PhotosUpload;

class PhotosController extends Controller
{
    public function indexAction()
    {
      $em = $this->getDoctrine()->getManager();
      $photos = $em->getRepository('GalaCoreBundle:Photos')->findAll();
      return $this->render('GalaCoreBundle:Photos:index.html.twig', array(
        'photos' => $photos,
      ));
    }

    public function photoAction(Request $request, $id)
    {
      $em = $this->getDoctrine()->getManager();
      $photo = $em->getRepository('GalaCoreBundle:Photos')->find($id);
      
      if (null == $photo) {
        return $this->redirect($this->generateUrl('gala_photos'));
      }
      
      $options = array();
      $user = $this->getUser();
      if ($user) {
        $form = $this->get('form.factory')->create(DeleteType::class);
        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
          $em->remove($photo);
          $em->flush();
          return $this->redirect($this->generateUrl('gala_photos'));
        }
        $options['form'] = $form->createView();
      }
      $options['photo'] = $photo;
      return $this->render('GalaCoreBundle:Photos:photo.html.twig', $options);
    }

    public function uploadAction(Request $request)
    {
      $photos = new PhotosUpload();
      $form = $this->get('form.factory')->create(PhotosType::class, $photos);
			if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
				$em = $this->getDoctrine()->getManager();
        foreach ($photos->getFiles() as $file) {
          $photo = new Photos();
          $photo->setFile($file);
          $em->persist($photo);
        }
				$em->flush();
				
				$request->getSession()->getFlashBag()->add('info', 'Image enregistrée.');
				
				return $this->redirect($request->getUri());
			}
      return $this->render('GalaCoreBundle:Photos:upload.html.twig', array(
        'form' => $form->createView(),
      ));
    }
}

src/Gala/CoreBundle/Resources/views/Photos/index.html.twig
{% extends "GalaCoreBundle::base.html.twig" %}

{% block title %}
  Photos - {{ parent() }}
{% endblock %}

{% block content %}
  {% if photos %}
    <div class="text-center">
      <h5>Photos</h5>
      <hr class="sm">
      <h3>Les photos du Gala sont désormais disponibles !</h3>
      <p>Nous avons mis en place un service de tirage photo à votre disposition.</p>
      <p>Cliquez sur votre photo, repérez son numéro et accédez à la billeterie !</p>
      <p>La livraison est gratuite !</p>
      <a href="http://event.pumpkin-app.com/pay/photoimtlilledouai" target="_blank"><button class="btn-gold">Billeterie</button></a>
    </div>
    <div class="flexbin flexbin-margin">
      {% for photo in photos %}
        <a href="{{ path('gala_photo', {'id': photo.id}) }}">
          <img alt="Photo #{{ photo.id }}" data-src="{{ asset(photo.fileUri | imagine_filter('thumb_300') ) }}"/>
        </a>
      {% endfor %}
    </div>
  {% else %}
  <h3>
    Les photos ne sont pas encore disponibles,<br /> veuillez repasser ultérieurement :)
  </h3>
  {% endif %}
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/8.6.0/lazyload.min.js"></script>
  <script>var myLazyLoad = new LazyLoad();</script>
{% endblock %}

src/Gala/CoreBundle/Resources/views/Photos/photo.html.twig
{% extends "GalaCoreBundle::base.html.twig" %}

{% block title %}
  Photo #{{ photo.id }} - {{ parent() }}
{% endblock %}

{% block content %}
<div class="text-center">
	<img alt="Photo #{{ photo.id }}" src="{{ asset(photo.fileUri) }}"/>
	<h3>Photo #{{ photo.id }}</h3>
	<a href="http://event.pumpkin-app.com/pay/photoimtlilledouai" target="_blank"><button class="btn-gold">Billeterie</button></a>
	{% if form is defined %}{{ form(form) }}{% endif %}
</div>
{% endblock %}

src/Gala/CoreBundle/Resources/views/Photos/upload.html.twig
{% extends "GalaCoreBundle::base.html.twig" %}

{% block content %}
  {{ form(form) }}
{% endblock %}